version: '3.8'

services:
  frontend:
    image: aramu/soup-frontend:2.1
    container_name: soup-frontend
    ports:
      - '3000:3000'
    environment:
      API_IP: soup-backend
    networks:
      - frontend-backend

  backend:
    image: 2214yj/soup-backend:2.1
    container_name: soup-backend
    ports:
      - '8000:8000'
    environment:
      spring.datasource.url: jdbc:mysql://soup-mysql:3306/soup?characterEncoding=UTF-8&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: pass123#
      spring.redis.host: soup-redis
      elasticsearch.host: soup-elasticsearch
      jwt.access-token.expire-length: 36000000
      jwt.refresh-token.expire-length: 12096000000
    networks:
      - ops_backend-db
      - frontend-backend


networks:
  frontend-backend: {}
  ops_backend-db:
    external: true
