version: "3.8"

services:
  mariadb:
    container_name: soup-mysql
    image: mysql:8.0
    volumes:
      - SampleDatabaseData:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=soup
      - MYSQL_ROOT_PASSWORD=pass123#
    restart: always

  redis:
    container_name: soup-redis
    image: redis:alpine3.16
    ports:
      - 6379:6379
    networks:
      - backend-db
    restart: always

  elasticsearch:
    container_name: soup-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend-db
    environment:
      - discovery.type=single-node
    restart: always

  kibana:
    container_name: soup-kibana
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - 5601:5601
    networks:
      - backend-db
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always

volumes:
  SampleDatabaseData:

networks:
  backend-db: {}